// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpbixsxzzbvqhzvlgymv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwYml4c3h6emJ2cWh6dmxneW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mjc5NDMsImV4cCI6MjA2NDEwMzk0M30.D-znGizMdtR3Ezr7UgjjuAX7s67WWqswjpRymg_sz5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);